/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// BudgetUsageApplyConfiguration represents a declarative configuration of the BudgetUsage type for use
// with apply.
type BudgetUsageApplyConfiguration struct {
	BudgetTotal *resource.Quantity `json:"budgetTotal,omitempty"`
	BudgetHours *int32             `json:"budgetHours,omitempty"`
}

// BudgetUsageApplyConfiguration constructs a declarative configuration of the BudgetUsage type for use with
// apply.
func BudgetUsage() *BudgetUsageApplyConfiguration {
	return &BudgetUsageApplyConfiguration{}
}

// WithBudgetTotal sets the BudgetTotal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BudgetTotal field is set to the value of the last call.
func (b *BudgetUsageApplyConfiguration) WithBudgetTotal(value resource.Quantity) *BudgetUsageApplyConfiguration {
	b.BudgetTotal = &value
	return b
}

// WithBudgetHours sets the BudgetHours field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BudgetHours field is set to the value of the last call.
func (b *BudgetUsageApplyConfiguration) WithBudgetHours(value int32) *BudgetUsageApplyConfiguration {
	b.BudgetHours = &value
	return b
}
