/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// WallTimeQuotaApplyConfiguration represents a declarative configuration of the WallTimeQuota type for use
// with apply.
type WallTimeQuotaApplyConfiguration struct {
	WallTimeHours *int32           `json:"wallTimeHours,omitempty"`
	Name          *v1.ResourceName `json:"name,omitempty"`
}

// WallTimeQuotaApplyConfiguration constructs a declarative configuration of the WallTimeQuota type for use with
// apply.
func WallTimeQuota() *WallTimeQuotaApplyConfiguration {
	return &WallTimeQuotaApplyConfiguration{}
}

// WithWallTimeHours sets the WallTimeHours field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WallTimeHours field is set to the value of the last call.
func (b *WallTimeQuotaApplyConfiguration) WithWallTimeHours(value int32) *WallTimeQuotaApplyConfiguration {
	b.WallTimeHours = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *WallTimeQuotaApplyConfiguration) WithName(value v1.ResourceName) *WallTimeQuotaApplyConfiguration {
	b.Name = &value
	return b
}
