/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// WallTimeFlavorUsageApplyConfiguration represents a declarative configuration of the WallTimeFlavorUsage type for use
// with apply.
type WallTimeFlavorUsageApplyConfiguration struct {
	Name          *kueuev1beta1.ResourceFlavorReference `json:"name,omitempty"`
	WallTimeUsage []WallTimeUsageApplyConfiguration     `json:"wallTimeUsage,omitempty"`
}

// WallTimeFlavorUsageApplyConfiguration constructs a declarative configuration of the WallTimeFlavorUsage type for use with
// apply.
func WallTimeFlavorUsage() *WallTimeFlavorUsageApplyConfiguration {
	return &WallTimeFlavorUsageApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *WallTimeFlavorUsageApplyConfiguration) WithName(value kueuev1beta1.ResourceFlavorReference) *WallTimeFlavorUsageApplyConfiguration {
	b.Name = &value
	return b
}

// WithWallTimeUsage adds the given value to the WallTimeUsage field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WallTimeUsage field.
func (b *WallTimeFlavorUsageApplyConfiguration) WithWallTimeUsage(values ...*WallTimeUsageApplyConfiguration) *WallTimeFlavorUsageApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithWallTimeUsage")
		}
		b.WallTimeUsage = append(b.WallTimeUsage, *values[i])
	}
	return b
}
