/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// WallTimeUsageApplyConfiguration represents a declarative configuration of the WallTimeUsage type for use
// with apply.
type WallTimeUsageApplyConfiguration struct {
	Name              *v1.ResourceName `json:"name,omitempty"`
	WallTimeAllocated *int32           `json:"wallTimeAllocated,omitempty"`
	WallTimeUsed      *int32           `json:"wallTimeUsed,omitempty"`
}

// WallTimeUsageApplyConfiguration constructs a declarative configuration of the WallTimeUsage type for use with
// apply.
func WallTimeUsage() *WallTimeUsageApplyConfiguration {
	return &WallTimeUsageApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *WallTimeUsageApplyConfiguration) WithName(value v1.ResourceName) *WallTimeUsageApplyConfiguration {
	b.Name = &value
	return b
}

// WithWallTimeAllocated sets the WallTimeAllocated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WallTimeAllocated field is set to the value of the last call.
func (b *WallTimeUsageApplyConfiguration) WithWallTimeAllocated(value int32) *WallTimeUsageApplyConfiguration {
	b.WallTimeAllocated = &value
	return b
}

// WithWallTimeUsed sets the WallTimeUsed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WallTimeUsed field is set to the value of the last call.
func (b *WallTimeUsageApplyConfiguration) WithWallTimeUsed(value int32) *WallTimeUsageApplyConfiguration {
	b.WallTimeUsed = &value
	return b
}
