/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// WallTimePolicyApplyConfiguration represents a declarative configuration of the WallTimePolicy type for use
// with apply.
type WallTimePolicyApplyConfiguration struct {
	WallTimeGroup               []WallTimeGroupApplyConfiguration `json:"wallTimeGroup,omitempty"`
	ActionWhenWallTimeExhausted *kueuev1beta1.StopPolicy          `json:"actionWhenWallTimeExhausted,omitempty"`
}

// WallTimePolicyApplyConfiguration constructs a declarative configuration of the WallTimePolicy type for use with
// apply.
func WallTimePolicy() *WallTimePolicyApplyConfiguration {
	return &WallTimePolicyApplyConfiguration{}
}

// WithWallTimeGroup adds the given value to the WallTimeGroup field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WallTimeGroup field.
func (b *WallTimePolicyApplyConfiguration) WithWallTimeGroup(values ...*WallTimeGroupApplyConfiguration) *WallTimePolicyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithWallTimeGroup")
		}
		b.WallTimeGroup = append(b.WallTimeGroup, *values[i])
	}
	return b
}

// WithActionWhenWallTimeExhausted sets the ActionWhenWallTimeExhausted field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActionWhenWallTimeExhausted field is set to the value of the last call.
func (b *WallTimePolicyApplyConfiguration) WithActionWhenWallTimeExhausted(value kueuev1beta1.StopPolicy) *WallTimePolicyApplyConfiguration {
	b.ActionWhenWallTimeExhausted = &value
	return b
}
